/opt/pytorch/nvfuser/python/nvfuser_direct/__init__.py:11: UserWarning: Be careful! You've imported nvfuser_direct when the nvfuser module is already imported.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformer_engine/__init__.py:59: RuntimeWarning: Detected a Jax installation but could not find the shared object file for the Transformer Engine Jax extension library. If this is not intentional, please reinstall Transformer Engine with `pip install transformer_engine[jax]` or build from source with `NVTE_FRAMEWORK=jax`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1605: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/Context.cpp:80.)
  _C._set_float32_matmul_precision(precision)
V0923 11:31:11.138000 44792 torch/_dynamo/guards.py:4181] [3/1] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:11.138000 44792 torch/_dynamo/guards.py:4181] [3/1] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:11.138000 44792 torch/_dynamo/guards.py:4181] [3/1] [__recompiles]     - 3/0: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:11.220000 44792 torch/_dynamo/guards.py:4181] [3/2] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:11.220000 44792 torch/_dynamo/guards.py:4181] [3/2] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:11.220000 44792 torch/_dynamo/guards.py:4181] [3/2] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:11.220000 44792 torch/_dynamo/guards.py:4181] [3/2] [__recompiles]     - 3/0: ___stack0['device_traces'][0][0]['addr'] == 0            # alloc = torch.cuda.memory_allocated(device=self.device_index)  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:53 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.249000 44792 torch/_dynamo/guards.py:4181] [3/3] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:20.249000 44792 torch/_dynamo/guards.py:4181] [3/3] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:20.249000 44792 torch/_dynamo/guards.py:4181] [3/3] [__recompiles]     - 3/2: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.249000 44792 torch/_dynamo/guards.py:4181] [3/3] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.249000 44792 torch/_dynamo/guards.py:4181] [3/3] [__recompiles]     - 3/0: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.337000 44792 torch/_dynamo/guards.py:4181] [3/4] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:20.337000 44792 torch/_dynamo/guards.py:4181] [3/4] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:20.337000 44792 torch/_dynamo/guards.py:4181] [3/4] [__recompiles]     - 3/3: ___stack0['device_traces'][0][1]['size'] == 65536        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.337000 44792 torch/_dynamo/guards.py:4181] [3/4] [__recompiles]     - 3/2: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.337000 44792 torch/_dynamo/guards.py:4181] [3/4] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.337000 44792 torch/_dynamo/guards.py:4181] [3/4] [__recompiles]     - 3/0: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles]     - 3/2: 5 <= ___stack0['device_traces'][0][0]['size']  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50 (_dynamo/variables/tensor.py:1435 in evaluate_expr)
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles]     - 3/4: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles]     - 3/3: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.426000 44792 torch/_dynamo/guards.py:4181] [3/5] [__recompiles]     - 3/0: ___stack0['device_traces'][0][0]['addr'] == 0            # alloc = torch.cuda.memory_allocated(device=self.device_index)  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:53 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     - 3/5: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     - 3/2: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     - 3/4: 5 <= ___stack0['device_traces'][0][1]['size']  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50 (_dynamo/variables/tensor.py:1435 in evaluate_expr)
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     - 3/3: ___stack0['device_traces'][0][1]['size'] == 65536        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.474000 44792 torch/_dynamo/guards.py:4181] [3/6] [__recompiles]     - 3/0: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/4: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/2: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/6: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/5: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/3: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.727000 44792 torch/_dynamo/guards.py:4181] [3/7] [__recompiles]     - 3/0: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles] Recompiling function torch_dynamo_resume_in_inner_fn_at_50 in /opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     triggered by the following guard failure(s):
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/7: len(___stack0['device_traces'][0]) == 4                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/4: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/2: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/6: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/5: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/3: len(___stack0['device_traces'][0]) == 3                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
V0923 11:31:20.866000 44792 torch/_dynamo/guards.py:4181] [3/8] [__recompiles]     - 3/0: len(___stack0['device_traces'][0]) == 1                  # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
W0923 11:31:20.867000 44792 torch/_dynamo/convert_frame.py:1355] [3/8] torch._dynamo hit config.recompile_limit (8)
W0923 11:31:20.867000 44792 torch/_dynamo/convert_frame.py:1355] [3/8]    function: 'torch_dynamo_resume_in_inner_fn_at_50' (/opt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:50)
W0923 11:31:20.867000 44792 torch/_dynamo/convert_frame.py:1355] [3/8]    last reason: 3/1: not ___stack0['device_traces'][0]                        # new_events = [event for event in events if event["size"] > 4]  # pt/pytorch/lightning-thunder/thunder/dev_utils/debug_memory_transform.py:52 in torch_dynamo_resume_in_inner_fn_at_50
W0923 11:31:20.867000 44792 torch/_dynamo/convert_frame.py:1355] [3/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0923 11:31:20.867000 44792 torch/_dynamo/convert_frame.py:1355] [3/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html
